package rest.database;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import com.google.gson.Gson;
import com.mongodb.*;
import com.mongodb.client.FindIterable;
import org.bson.Document;
import org.bson.types.ObjectId;
import org.json.JSONException;
import org.json.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import rest.models.User;

/*
The database class. For now we use a local database, you need to download and start MongoDB as a service, call it "HouseDatabase".
Use the correct port for your server.


*/

public class Database {
    private Gson gson;
    private MongoClient mongoClient = null;
    private DB databaseObj = null;
    private static Database database = Database.getInstance();
    private DBCollection dbCollection;
    private BasicDBObject document, query;
    private DBCursor cursor;
    private DBObject fetchedObject;

    private FindIterable<Document> findIterable;


    public static void main(String[] args) {
/*
        Object object = Database.getInstance().getDeviceId("1234");
        String status = Database.getInstance().getDeviceStatus(object);
        System.out.println(status);

        Object mongoObjectId = database.getDeviceId("1234");
        Database.getInstance().findUser("1234-abcd-12dc");
        Database.getInstance().changeStatusOfDevice(object);
        System.out.println("MongoObjectId " + mongoObjectId.toString());
        database.changeStatusOfDevice(mongoObjectId);
                System.out.println(database.loginMethod("hej"));

*/
        Object object = Database.getInstance().getDeviceId("1337");
        System.out.println(object.toString());
        String status = Database.getInstance().getDeviceStatus(object);
        String changedState = Database.getInstance().changeStatusOfDevice(object);
        System.out.println(changedState);
    }


    private Database() {
        mongoClient = new MongoClient("localhost", 27017);
        databaseObj = mongoClient.getDB("HouseDatabase");

    }

/*
To get the object id(mongoDB's object ID, looks like: "5dc199596d60d45f6409d791"),
use the method "getObjectId", which returns the object ID.
The method uses "our" object id notation (e.g. 1234, as protocol states)

 */

    public String getDeviceStatus(Object id) {
        if (id.toString().equalsIgnoreCase("No such id exist")) {
            return "No such id exist";
        }

        dbCollection = databaseObj.getCollection("Device");
        document = new BasicDBObject();

        document.put("_id", id);
        cursor = dbCollection.find(document);
        fetchedObject = cursor.next();

        return fetchedObject.get("state").toString();

    }

    public String changeStatusOfDevice(Object objectId) {
        dbCollection = databaseObj.getCollection("Device");
        //   document = new BasicDBObject();
        // document.put("_id", objectId.toString());
        query = new BasicDBObject();
        query.append("$set", new BasicDBObject().append("state", "1"));
        document = new BasicDBObject();
        document.append("id", "1337");
        dbCollection.update(document,query);


        return "";
    }

    public Object getDeviceId(String id) { //Returns the actual mongoDB id, which is 12byte autogenerated unique id
        dbCollection = databaseObj.getCollection("Device");

        document = new BasicDBObject();
        document.put("id", id);
        cursor = dbCollection.find(document);

        if (!cursor.hasNext()) {
            return "No such id exist";
        }
        fetchedObject = cursor.next();


        return fetchedObject.get("_id");
    }


    /*
    Create user class. Takes a JsonString as parameter which is parsed into a java object and then created if email and username is available
     */
    public String createUser(String jsonString) {
        try {
         /*   JSONObject filipTest = new JSONObject();
            filipTest.put("firstName", "Filip");
            filipTest.put("lastName", "BenkanssonjAO");
            filipTest.put("password", "123456");
            filipTest.put("userName", "Benka33");
            filipTest.put("userId", "5c37692c-360f-4022-a7db-23a45f828c1d");
            filipTest.put("email", "sm@somethingmore.com");
            jsonString = filipTest.toString();  //"den som kommer från server"
*/
            dbCollection = databaseObj.getCollection("User");
            gson = new Gson();
            User user = gson.fromJson(jsonString, User.class);
            String userEmail = user.getEmail();
            String userName = user.getUserName();

            document = new BasicDBObject();
            document.put("email", userEmail);
            cursor = dbCollection.find(document);

            while (cursor.hasNext()) {
                fetchedObject = cursor.next();
                if (fetchedObject.toString().contains(userEmail)) {

                    return "0"; //Email already in use
                } else if (fetchedObject.toString().contains(userName)) {

                    return "0"; //User name already in use
                }

            }

            query = new BasicDBObject();
            query.put("firstName", user.getFirstName());
            query.put("lastName", user.getLastName());
            query.put("password", user.getPassword());
            query.put("userName", user.getUserName());
            query.put("userId", user.getUserId());
            query.put("email", user.getEmail());

            //   dbCollection.insert(query);

        } catch (JSONException ex) {
            ex.printStackTrace();
            return "0"; //Unexpected error caught
        }

        return "1"; //Successful

    }

    //Find user; egentligen, behöver iv den?
    public Object findUser(String id) {
        dbCollection = databaseObj.getCollection("User");

        document = new BasicDBObject();
        document.put("userId", id);
        cursor = dbCollection.find(document);

        if (cursor.hasNext()) {
            fetchedObject = cursor.next();

        }

        fetchedObject = cursor.next();


        return fetchedObject;


    }


    public String loginMethod(String jsonString) {
       /* JSONObject testObject = new JSONObject();
        testObject.put("userName", "IsakZ");
        testObject.put("password", "123");
        jsonString = testObject.toString();
*/
        dbCollection = databaseObj.getCollection("User");
        document = new BasicDBObject();
        gson = new Gson();
        User user = gson.fromJson(jsonString, User.class);
        document.put("userName", user.getUserName());
        document.put("password", user.getPassword());
        System.out.println(user.getUserName());
        System.out.println(user.getPassword());

        cursor = dbCollection.find(document);


        while (cursor.hasNext()) {
            fetchedObject = cursor.next();

            if (fetchedObject.toString().contains(user.getUserName())) {
                if (fetchedObject.toString().contains(user.getPassword())) {

                    return "1"; //Login successful
                } else {
                    return "0"; //Incorrect password
                }


            } else {
                return "0"; //Incorrect username
            }

        }

        return "0"; //Big fail eggs de

    }


    public static Database getInstance() {
        if (database == null) {

            database = new Database();
        }
        return database;


    }


}
